// Salesforce "Service" picklist. Each value is identical to its API name, so
// the selected label is sent to the API as-is.
export const SERVICE_OPTIONS = [
  'Appliances',
  'Architect Fee',
  'Asphalt',
  'Cabinets Hardware Allowance',
  'Cabinets and Vanity Allowance',
  'Cabinets and Vanity Installation',
  'Carpet Allowance',
  'Countertop Allowance',
  'Demo',
  'Door Hardware Allowance',
  'Drywall',
  'Electrical',
  'Excavation & Concrete',
  'Exterior Door Allowance',
  'Finish Carpentry',
  'Framing',
  'Garage Doors',
  'General Conditions',
  'Glazing and Mirror Allowance',
  'Gutters and Downspouts',
  'HVAC',
  'Hardwood Flooring',
  'Insulation',
  'Interior Door Allowance',
  'LVT Flooring',
  'Landscape Allowance',
  'Light Fixtures Allowance',
  'Low Voltage',
  'Masonry',
  'Material',
  'Painting Exterior',
  'Painting Interior',
  'Permit',
  'Plumbing',
  'Plumbing Fixtures Allowance',
  'Radon Mitigation',
  'Roof',
  'Service',
  'Sewer Service',
  'Siding',
  'Skylight',
  'Stairs',
  'Structural Steel',
  'Stucco',
  'Temporary Utilities',
  'Tiles',
  'Tiles Allowance',
  'Water Service',
  'Windows',
];
